"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Check, MapPin, Package, Truck } from "lucide-react";
import { useI18n } from "@/lib/i18n-context";

const steps=["route","cargo","vehicle","date","publish"] as const;
export default function NewShipmentPage(){const {text}=useI18n();const [step,setStep]=useState(0);const [done,setDone]=useState(false);return <div className="mx-auto max-w-3xl"><Link href="/shipments" className="inline-flex items-center gap-2 text-sm font-bold text-gray-500"><ArrowLeft size={16}/>{text("back")}</Link><div className="mt-5"><p className="text-sm font-bold text-teal-700">RohBar</p><h1 className="mt-1 text-3xl font-black">{text("create")}</h1><div className="mt-6 flex gap-2">{steps.map((s,i)=><div key={s} className={`h-1.5 flex-1 rounded-full ${i<=step?"bg-teal-700":"bg-gray-200"}`}/>)}</div></div>{done?<Success/>:<div className="mt-7 rounded-3xl border bg-white p-5 sm:p-8"><div className="grid gap-5 sm:grid-cols-2">{step===0&&<><Field label={text("from")} placeholder="Москва" icon={<MapPin size={17}/>}/><Field label={text("to")} placeholder="Казань" icon={<MapPin size={17}/>}/></>}{step===1&&<><Field label={text("cargo")} placeholder="Строительные материалы" icon={<Package size={17}/>}/><Field label={text("weight")} placeholder="20 т" icon={<Package size={17}/>}/></>}{step===2&&<><Field label={text("vehicle")} placeholder="Тент" icon={<Truck size={17}/>}/><Field label="Кузов" placeholder="Тентованный" icon={<Truck size={17}/>}/></>}{step===3&&<><Field label={text("date")} placeholder="10 сентября 2026"/><Field label="Время" placeholder="09:00"/></>}{step===4&&<div className="sm:col-span-2 rounded-2xl bg-gray-50 p-5"><p className="font-bold">Проверьте заявку</p><p className="mt-2 text-sm leading-6 text-gray-600">Маршрут, параметры груза, транспорт и дата будут отправлены в API после подключения backend.</p></div>}</div><div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between">{step>0?<button onClick={()=>setStep(step-1)} className="rounded-xl border px-5 py-3 font-bold">{text("back")}</button>:<span/>}<button onClick={()=>step<4?setStep(step+1):setDone(true)} className="rounded-xl bg-teal-700 px-6 py-3 font-bold text-white">{step<4?text("next"):text("publish")}</button></div></div>}</div>}
function Field({label,placeholder,icon}:{label:string;placeholder:string;icon?:React.ReactNode}){return <label><span className="mb-2 block text-sm font-bold">{label}</span><div className="flex items-center gap-2 rounded-xl border px-3.5 py-3 focus-within:border-teal-600">{icon}<input className="w-full outline-none" placeholder={placeholder}/></div></label>}
function Success(){return <div className="mt-8 rounded-3xl border bg-white p-10 text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-teal-50 text-teal-700"><Check size={30}/></div><h2 className="mt-5 text-2xl font-black">Заявка готова</h2><p className="mx-auto mt-2 max-w-md text-gray-500">Frontend уже подготовлен для отправки этой формы в backend API и запуска автоматических workflow.</p><Link href="/dashboard" className="mt-6 inline-flex rounded-xl bg-teal-700 px-6 py-3 font-bold text-white">Открыть кабинет</Link></div>}
