"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { Bell, Boxes, ClipboardList, Home, Menu, Plus, Search, Truck, UserRound, X } from "lucide-react";
import { useState } from "react";
import { I18nProvider, useI18n } from "@/lib/i18n-context";

function Shell({children}:{children:React.ReactNode}){ const [open,setOpen]=useState(false); const path=usePathname(); const {text,locale,setLocale}=useI18n(); const links=[{href:"/dashboard",icon:Home,label:text("home")},{href:"/shipments",icon:Search,label:text("shipments")},{href:"/shipments/new",icon:Plus,label:text("create")},{href:"/fleet",icon:Truck,label:text("fleet")},{href:"/profile",icon:UserRound,label:text("profile")}]; return <div className="min-h-screen"><header className="glass sticky top-0 z-40 border-b border-gray-200/80"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-2 font-black text-xl tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-teal-700 text-white">R</span>{text("brand")}</Link><div className="hidden items-center gap-2 md:flex"><Link href="/shipments/new" className="rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-bold text-white">{text("create")}</Link><button onClick={()=>setLocale(locale==="ru"?"tg":"ru")} className="rounded-xl border px-3 py-2 text-sm font-semibold">{locale.toUpperCase()}</button><Link href="/profile" className="grid size-10 place-items-center rounded-full bg-gray-100"><UserRound size={18}/></Link></div><button className="md:hidden" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header><div className="mx-auto flex max-w-7xl"><aside className={`fixed inset-y-16 left-0 z-30 w-72 border-r bg-white p-4 transition-transform md:sticky md:top-16 md:block md:h-[calc(100vh-4rem)] md:translate-x-0 ${open?"translate-x-0":"-translate-x-full"}`}><nav className="space-y-1">{links.map(({href,icon:Icon,label})=><Link key={href} href={href} onClick={()=>setOpen(false)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${path===href?"bg-teal-50 text-teal-800":"text-gray-600 hover:bg-gray-50"}`}><Icon size={19}/>{label}</Link>)}</nav><div className="mt-6 border-t pt-5"><Link href="/notifications" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-gray-600"><Bell size={19}/>{text("notifications")}</Link><Link href="/settings" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold text-gray-600"><Boxes size={19}/>{text("settings")}</Link></div></aside><main className="min-w-0 flex-1 px-4 py-6 pb-24 sm:px-6 lg:px-8">{children}</main></div><nav className="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 px-2 py-2 backdrop-blur md:hidden safe-bottom"><div className="grid grid-cols-5">{links.map(({href,icon:Icon,label})=><Link key={href} href={href} className={`flex flex-col items-center gap-1 py-1 text-[11px] ${path===href?"text-teal-700":"text-gray-500"}`}><Icon size={20}/><span>{label}</span></Link>)}</div></nav></div> }
export function AppShell({children}:{children:React.ReactNode}){return <I18nProvider><Shell>{children}</Shell></I18nProvider>}
