import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, MapPin, Package, Truck, type LucideIcon } from "lucide-react";
import type { ShipmentStatus } from "@/types";

export function PageHeader({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow&&<p className="mb-2 text-xs font-bold uppercase tracking-[.16em] text-teal-700">{eyebrow}</p>}<h1 className="text-3xl font-black tracking-tight sm:text-4xl">{title}</h1>{description&&<p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500 sm:text-base">{description}</p>}</div>{action}</div>}
export function Button({children,href,variant="primary",type="button",className=""}:{children:ReactNode;href?:string;variant?:"primary"|"secondary"|"ghost";type?:"button"|"submit";className?:string}){const styles={primary:"bg-teal-700 text-white hover:bg-teal-800",secondary:"border border-slate-200 bg-white text-slate-900 hover:bg-slate-50",ghost:"text-slate-600 hover:bg-slate-100"}[variant];const cls=`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-bold transition ${styles} ${className}`;return href?<Link href={href} className={cls}>{children}</Link>:<button type={type} className={cls}>{children}</button>}
export function Card({children,className=""}:{children:ReactNode;className?:string}){return <section className={`rounded-3xl border border-slate-200/80 bg-white p-5 shadow-[0_8px_30px_rgba(15,23,42,.04)] sm:p-6 ${className}`}>{children}</section>}
export function StatCard({icon:Icon,label,value,detail}:{icon:LucideIcon;label:string;value:string;detail?:string}){return <Card><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-teal-50 text-teal-700"><Icon size={21}/></span>{detail&&<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-700">{detail}</span>}</div><p className="mt-5 text-sm text-slate-500">{label}</p><p className="mt-1 text-2xl font-black tracking-tight">{value}</p></Card>}
const statusText:Record<ShipmentStatus,string>={published:"Опубликована",offered:"Есть предложения",accepted:"Принята",in_transit:"В пути",delivered:"Доставлена",completed:"Завершена"};
export function StatusBadge({status}:{status:ShipmentStatus}){const tone=status==="completed"||status==="delivered"?"bg-emerald-50 text-emerald-700":status==="in_transit"?"bg-blue-50 text-blue-700":status==="accepted"?"bg-violet-50 text-violet-700":"bg-amber-50 text-amber-700";return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-bold ${tone}`}>{statusText[status]}</span>}
export function ShipmentCard({id,from,to,date,cargo,weight,vehicle,price,status,company}:{id:string;from:string;to:string;date:string;cargo:string;weight:string;vehicle:string;price:string;status:ShipmentStatus;company:string}){return <Card><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2 text-xs font-bold text-slate-400"><span>{id}</span><StatusBadge status={status}/></div><div className="mt-3 flex flex-wrap items-center gap-2 text-lg font-black"><span>{from}</span><ArrowRight size={18} className="text-teal-600"/><span>{to}</span></div></div><div className="sm:text-right"><p className="text-xs text-slate-400">Стоимость</p><p className="mt-1 text-xl font-black">{price}</p></div></div><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-4"><Info icon={MapPin} label="Дата" value={date}/><Info icon={Package} label="Груз" value={`${cargo} · ${weight}`}/><Info icon={Truck} label="Транспорт" value={vehicle}/><Info icon={MapPin} label="Заказчик" value={company}/></div><div className="mt-5 flex justify-end"><Button href={`/shipments/${id}`} variant="secondary">Подробнее <ArrowRight size={16}/></Button></div></Card>}
function Info({icon:Icon,label,value}:{icon:LucideIcon;label:string;value:string}){return <div className="flex gap-2"><Icon size={16} className="mt-0.5 shrink-0 text-slate-400"/><div><p className="text-[11px] font-bold uppercase tracking-wide text-slate-400">{label}</p><p className="mt-1 text-sm font-semibold text-slate-700">{value}</p></div></div>}
export function Field({label,children,required}:{label:string;children:ReactNode;required?:boolean}){return <label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">{label}{required&&<span className="text-red-500"> *</span>}</span>{children}</label>}
export const inputClass="h-12 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm font-medium outline-none transition placeholder:text-slate-400 focus:border-teal-600 focus:ring-4 focus:ring-teal-600/10";
