"use client";
import Link from "next/link";
import { Activity, ArrowUpRight, Bell, CheckCircle2, Clock3, Plus, Truck, WalletCards, PackageCheck } from "lucide-react";
import { Button, Card, PageHeader, StatCard } from "@/components/rohbar-ui";
import { useSyncExternalStore } from "react";
import { getStoredRole, roleLabel } from "@/lib/session";
import type { Role } from "@/types";

const shipments=[{id:"RH-10482",route:"Москва → Казань",status:"В пути",date:"10 сен",price:"85 000 ₽"},{id:"RH-10479",route:"Санкт-Петербург → Москва",status:"Принята",date:"11 сен",price:"72 000 ₽"},{id:"RH-10471",route:"Екатеринбург → Самара",status:"Есть предложения",date:"12 сен",price:"64 000 ₽"}];
const subscribeRole=()=>{window.addEventListener("storage",handleRoleChange);return()=>window.removeEventListener("storage",handleRoleChange)};
const handleRoleChange=()=>{};

export default function Dashboard(){const role=useSyncExternalStore(subscribeRole,getStoredRole,()=>"customer" as Role);const carrier=role==="carrier";const driver=role==="driver";const admin=role==="admin";return <div className="mx-auto max-w-7xl"><PageHeader eyebrow={`RohBar · ${roleLabel(role)}`} title={carrier?"Кабинет перевозчика":driver?"Мои рейсы":admin?"Центр управления":"Обзор"} description={carrier?"Находите загрузки, управляйте автопарком и принятыми перевозками.":driver?"Контролируйте назначенные рейсы и статусы доставки.":admin?"Контроль платформы, пользователей и операций.":"Единый центр управления заявками и перевозками."} action={!driver&&!admin?<Button href={carrier?"/shipments":"/shipments/new"}><Plus size={18}/>{carrier?"Найти загрузку":"Создать заявку"}</Button>:undefined}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={Truck} label={carrier?"Активные рейсы":"Активные перевозки"} value={carrier?"14":"8"} detail="+2"/><StatCard icon={Clock3} label={carrier?"Новые заявки":"На рассмотрении"} value={carrier?"27":"12"}/><StatCard icon={carrier?WalletCards:CheckCircle2} label={carrier?"Выручка за месяц":"Завершено"} value={carrier?"1,24 млн ₽":"146"} detail={carrier?"+12%":"+8%"}/><StatCard icon={admin?Activity:PackageCheck} label={admin?"Ошибки API":"Выполнение"} value={admin?"0":"96%"}/></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Card><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">{carrier?"Доступные и активные заявки":driver?"Назначенные рейсы":"Последние перевозки"}</h2><p className="mt-1 text-sm text-slate-500">Состояние операций RohBar</p></div><Link href="/shipments" className="text-sm font-bold text-teal-700">Все <ArrowUpRight size={15} className="inline"/></Link></div><div className="mt-4 divide-y divide-slate-100">{shipments.map(item=><div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex gap-2 text-xs font-bold text-slate-400"><span>{item.id}</span><span>·</span><span>{item.date}</span></div><p className="mt-1 font-black">{item.route}</p><p className="mt-1 text-sm text-slate-500">{carrier?"Готова к отклику":driver?"Назначен рейс":item.status}</p></div><p className="text-base font-black">{item.price}</p></div>)}</div></Card><Card><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Уведомления</h2><p className="mt-1 text-sm text-slate-500">Последние события и automation</p></div><Bell size={19} className="text-slate-400"/></div><div className="mt-5 space-y-3">{["Получено новое предложение по RH-10482","Перевозка RH-10479 принята","Проверьте документы перевозчика"].map(text=><div key={text} className="rounded-2xl bg-slate-50 p-4 text-sm font-semibold leading-5">{text}</div>)}</div><Button href="/notifications" variant="secondary" className="mt-5 w-full">Все уведомления</Button></Card></div></div>}
