import Link from "next/link";
import { Activity, ArrowUpRight, Bell, CheckCircle2, Clock3, Plus, Truck } from "lucide-react";
import { Button, Card, PageHeader, StatCard } from "@/components/rohbar-ui";

const shipments=[
 {id:"RH-10482",route:"Москва → Казань",status:"В пути",date:"10 сен",price:"85 000 ₽"},
 {id:"RH-10479",route:"Санкт-Петербург → Москва",status:"Принята",date:"11 сен",price:"72 000 ₽"},
 {id:"RH-10471",route:"Екатеринбург → Самара",status:"Есть предложения",date:"12 сен",price:"64 000 ₽"},
];

export default function Dashboard(){return <div className="mx-auto max-w-7xl"><PageHeader eyebrow="RohBar" title="Обзор" description="Единый центр управления заявками, перевозками и автопарком." action={<Button href="/shipments/new"><Plus size={18}/>Создать заявку</Button>}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={Truck} label="Активные перевозки" value="8" detail="+2"/><StatCard icon={Clock3} label="На рассмотрении" value="12"/><StatCard icon={CheckCircle2} label="Завершено" value="146" detail="+8%"/><StatCard icon={Activity} label="Выполнение" value="96%"/></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Card><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Последние перевозки</h2><p className="mt-1 text-sm text-slate-500">Текущие заявки и их состояние</p></div><Link href="/shipments" className="text-sm font-bold text-teal-700">Все <ArrowUpRight size={15} className="inline"/></Link></div><div className="mt-4 divide-y divide-slate-100">{shipments.map(item=><div key={item.id} className="flex flex-col gap-3 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex gap-2 text-xs font-bold text-slate-400"><span>{item.id}</span><span>·</span><span>{item.date}</span></div><p className="mt-1 font-black">{item.route}</p><p className="mt-1 text-sm text-slate-500">{item.status}</p></div><p className="text-base font-black">{item.price}</p></div>)}</div></Card><Card><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Уведомления</h2><p className="mt-1 text-sm text-slate-500">Последние события</p></div><Bell size={19} className="text-slate-400"/></div><div className="mt-5 space-y-3">{["Получено новое предложение по RH-10482","Перевозка RH-10479 принята","Проверьте документы перевозчика"].map(text=><div key={text} className="rounded-2xl bg-slate-50 p-4 text-sm font-semibold leading-5">{text}</div>)}</div><Button href="/notifications" variant="secondary" className="mt-5 w-full">Все уведомления</Button></Card></div></div>}
