"use client";
import Link from "next/link";
import { ArrowUpRight, Clock3, MapPin, Package, Truck } from "lucide-react";
import { useI18n } from "@/lib/i18n-context";
import type { Shipment } from "@/types";

const shipments:Shipment[]=[{id:"RH-10482",from:"Москва",to:"Казань",date:"Сегодня, 18:00",cargo:"Строительные материалы",weight:"20 т",vehicle:"Тент",price:"85 000 ₽",status:"offered",company:"Вектор Логистик"},{id:"RH-10481",from:"Санкт-Петербург",to:"Москва",date:"Завтра, 09:00",cargo:"Продукты",weight:"10 т",vehicle:"Рефрижератор",price:"72 000 ₽",status:"published",company:"Nord Cargo"},{id:"RH-10479",from:"Екатеринбург",to:"Самара",date:"10 сен, 07:30",cargo:"Оборудование",weight:"8 т",vehicle:"Тент",price:"64 000 ₽",status:"accepted",company:"Урал Транс"}];
export default function ShipmentsPage(){const {text}=useI18n();return <div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold text-teal-700">RohBar</p><h1 className="mt-1 text-3xl font-black">{text("shipments")}</h1><p className="mt-2 text-gray-500">Заявки, которые можно подобрать под ваш транспорт.</p></div><Link href="/shipments/new" className="rounded-xl bg-teal-700 px-5 py-3 text-center font-bold text-white">+ {text("create")}</Link></div><div className="mt-6 grid gap-3 sm:grid-cols-4"><Input label={text("from")} value="" placeholder="Город"/><Input label={text("to")} value="" placeholder="Город"/><Input label={text("date")} value="" placeholder="Любая дата"/><button className="rounded-xl border bg-white px-4 py-3 text-sm font-bold sm:mt-6">{text("filter")}</button></div><div className="mt-7 space-y-3">{shipments.map(s=><article key={s.id} className="rounded-2xl border bg-white p-5 transition hover:shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-xs font-bold text-teal-800">{text(s.status)}</span><span className="text-xs text-gray-400">{s.id}</span></div><div className="mt-3 flex flex-wrap items-center gap-2 text-lg font-black"><MapPin size={18} className="text-teal-700"/>{s.from}<span className="text-gray-300">→</span>{s.to}</div><div className="mt-2 flex flex-wrap gap-4 text-sm text-gray-500"><span className="inline-flex items-center gap-1"><Package size={15}/>{s.cargo}</span><span>{s.weight}</span><span className="inline-flex items-center gap-1"><Truck size={15}/>{s.vehicle}</span><span className="inline-flex items-center gap-1"><Clock3 size={15}/>{s.date}</span></div></div><div className="flex items-center justify-between border-t pt-4 lg:w-48 lg:border-0 lg:pt-0"><div><p className="text-xs text-gray-500">{text("price")}</p><p className="text-xl font-black">{s.price}</p></div><Link href={`/shipments/${s.id}`} className="grid size-10 place-items-center rounded-xl bg-gray-100"><ArrowUpRight size={18}/></Link></div></div></article>)}</div></div>}
function Input({label,placeholder}:{label:string;value:string;placeholder:string}){return <label className="block"><span className="mb-1.5 block text-xs font-bold text-gray-500">{label}</span><input className="w-full rounded-xl border bg-white px-3.5 py-3 outline-none focus:border-teal-600" placeholder={placeholder}/></label>}
