mod telegram;

use argon2::{password_hash::{PasswordHash, PasswordHasher, PasswordVerifier, SaltString}, Argon2};
use axum::{extract::{Path, Query, State, WebSocketUpgrade}, http::{header, HeaderMap, HeaderValue, StatusCode}, response::{sse::{Event, KeepAlive, Sse}, IntoResponse, Response}, routing::{get, post}, Json, Router};
use axum::extract::ws::{Message, WebSocket};
use chrono::{DateTime, Utc};
use hmac::{Hmac, Mac};
use redis::AsyncCommands;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use sha2::Sha256;
use sqlx::{postgres::PgPoolOptions, FromRow, PgPool};
use std::{convert::Infallible, env, sync::Arc};
use tokio::sync::broadcast;
use tokio_stream::{wrappers::BroadcastStream, StreamExt};
use tower_http::{cors::CorsLayer, trace::TraceLayer};
use tracing::{error, info};
use uuid::Uuid;

type HmacSha256=Hmac<Sha256>;
pub type SharedState=Arc<AppState>;

pub struct AppState{pub db:PgPool,pub redis:redis::Client,pub realtime:broadcast::Sender<RealtimeMessage>,pub telegram_token:Option<String>,pub telegram_webhook_secret:Option<String>,pub session_cookie_secure:bool,pub frontend_origin:String,pub automation_secret:Option<String>}
#[derive(Clone,Serialize)]pub struct RealtimeMessage{r#type:String,shipment:Option<Shipment>,event:Option<ShipmentEvent>,notification:Option<Value>}
#[derive(Clone,Serialize,Deserialize,FromRow)]pub struct User{id:Uuid,name:String,role:String,phone:Option<String>,telegram_id:Option<i64>}
#[derive(Clone,Serialize,Deserialize,FromRow)]pub struct Shipment{id:String,#[serde(rename="from")]from_city:String,#[serde(rename="to")]to_city:String,date:String,cargo:String,weight:String,vehicle:String,price:String,status:String,company:String}
#[derive(Clone,Serialize,Deserialize,FromRow)]pub struct ShipmentEvent{id:Uuid,shipment_id:String,event:String,actor_id:Uuid,payload:Value,occurred_at:DateTime<Utc>}
#[derive(Serialize,FromRow)]pub struct Offer{id:String,shipment_id:String,carrier_id:Uuid,carrier_name:String,vehicle:String,price:String,eta:String,status:String}
#[derive(Serialize,FromRow)]pub struct FleetVehicle{id:String,plate:String,model:String,body:String,capacity:String,volume:String,status:String,driver_name:Option<String>}
#[derive(Serialize,FromRow)]pub struct DriverAssignment{shipment_id:String,driver_id:Uuid,driver_name:String,phone:Option<String>,vehicle_id:Option<String>,vehicle_plate:Option<String>}
#[derive(Serialize,FromRow)]pub struct NotificationItem{id:Uuid,title:String,text:String,r#type:String,read:bool,created_at:DateTime<Utc>}
#[derive(Deserialize)]struct Credentials{email:String,password:String}
#[derive(Deserialize)]struct RegisterInput{name:String,email:String,password:String,role:String,phone:Option<String>}
#[derive(Deserialize)]struct TelegramAuth{#[serde(rename="initData")]init_data:String}
#[derive(Deserialize)]struct StatusInput{status:String}
#[derive(Deserialize)]struct OfferInput{vehicle:String,price:String,eta:String}
#[derive(Deserialize)]struct DriverInput{driver_id:Uuid,driver_name:String,phone:Option<String>,vehicle_id:Option<String>,vehicle_plate:Option<String>}
#[derive(Deserialize)]struct EventInput{id:Uuid,event:String,aggregate_id:String,payload:Value}
#[derive(Deserialize)]struct RealtimeQuery{shipment_id:Option<String>}

fn ok<T:Serialize>(data:T)->Json<Value>{Json(json!({"data":data,"meta":{"requestId":Uuid::new_v4(),"cursor":null}}))}
fn err(status:StatusCode,code:&str,message:&str)->Response{(status,Json(json!({"error":{"code":code,"message":message}}))).into_response()}
fn cookie_token(h:&HeaderMap)->Option<String>{h.get(header::COOKIE)?.to_str().ok()?.split(';').find_map(|v|v.trim().strip_prefix("rohbar_session=").map(str::to_owned))}
async fn user(s:&SharedState,h:&HeaderMap)->Option<User>{let token=cookie_token(h)?;sqlx::query_as::<_,User>("SELECT u.id,u.name,u.role,u.phone,u.telegram_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=$1 AND s.expires_at>NOW()").bind(token).fetch_optional(&s.db).await.ok().flatten()}
fn set_cookie(token:&str,secure:bool)->String{format!("rohbar_session={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=604800{}",if secure{"; Secure"}else{""})}
async fn new_session(s:&SharedState,id:Uuid)->Result<String,sqlx::Error>{let token=Uuid::new_v4().to_string();sqlx::query("INSERT INTO sessions(token,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '7 days')").bind(&token).bind(id).execute(&s.db).await?;Ok(token)}

async fn health(State(s):State<SharedState>)->Response{let db=sqlx::query_scalar::<_,i32>("SELECT 1").fetch_one(&s.db).await.is_ok();let redis=match s.redis.get_multiplexed_async_connection().await{Ok(mut c)=>c.ping::<String>().await.is_ok(),Err(_)=>false};ok(json!({"status":if db&&redis{"ok"}else{"degraded"},"database":db,"redis":redis})).into_response()}
async fn about(State(s):State<SharedState>)->Response{ok(json!({"name":"RohBar","description":"Цифровая платформа межгородских грузоперевозок","version":env!("CARGO_PKG_VERSION"),"realtime":{"websocket":true,"sse":true},"automation":true,"telegramEnabled":s.telegram_token.is_some()})).into_response()}
async fn me(State(s):State<SharedState>,h:HeaderMap)->Response{match user(&s,&h).await{Some(v)=>ok(v).into_response(),None=>err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")}}
async fn login(State(s):State<SharedState>,Json(i):Json<Credentials>)->Response{let row=sqlx::query_as::<_,(User,String)>("SELECT id,name,role,phone,telegram_id,password_hash FROM users WHERE email=$1").bind(&i.email).fetch_optional(&s.db).await.ok().flatten();let Some((u,hash))=row else{return err(StatusCode::UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid credentials")};let Ok(ph)=PasswordHash::new(&hash)else{return err(StatusCode::INTERNAL_SERVER_ERROR,"PASSWORD_HASH_ERROR","Invalid password hash")};if Argon2::default().verify_password(i.password.as_bytes(),&ph).is_err(){return err(StatusCode::UNAUTHORIZED,"INVALID_CREDENTIALS","Invalid credentials")};let Ok(t)=new_session(&s,u.id).await else{return err(StatusCode::INTERNAL_SERVER_ERROR,"SESSION_ERROR","Could not create session")};let mut r=ok(u).into_response();r.headers_mut().insert(header::SET_COOKIE,HeaderValue::from_str(&set_cookie(&t,s.session_cookie_secure)).unwrap());r}
async fn register(State(s):State<SharedState>,Json(i):Json<RegisterInput>)->Response{if !matches!(i.role.as_str(),"customer"|"carrier"|"driver"){return err(StatusCode::BAD_REQUEST,"VALIDATION_ERROR","Unsupported role")};if i.password.len()<8||i.name.trim().len()<2{return err(StatusCode::BAD_REQUEST,"VALIDATION_ERROR","Name and password do not meet requirements")};let salt=SaltString::generate(&mut rand::thread_rng());let Ok(hash)=Argon2::default().hash_password(i.password.as_bytes(),&salt).map(|x|x.to_string())else{return err(StatusCode::INTERNAL_SERVER_ERROR,"PASSWORD_HASH_ERROR","Could not hash password")};let u=sqlx::query_as::<_,User>("INSERT INTO users(id,email,name,password_hash,role,phone) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,role,phone,telegram_id").bind(Uuid::new_v4()).bind(i.email).bind(i.name).bind(hash).bind(i.role).bind(i.phone).fetch_one(&s.db).await;let Ok(u)=u else{return err(StatusCode::CONFLICT,"EMAIL_EXISTS","Email already exists")};let Ok(t)=new_session(&s,u.id).await else{return err(StatusCode::INTERNAL_SERVER_ERROR,"SESSION_ERROR","Could not create session")};let mut r=ok(u).into_response();r.headers_mut().insert(header::SET_COOKIE,HeaderValue::from_str(&set_cookie(&t,s.session_cookie_secure)).unwrap());r}
async fn logout(State(s):State<SharedState>,h:HeaderMap)->Response{if let Some(t)=cookie_token(&h){let _=sqlx::query("DELETE FROM sessions WHERE token=$1").bind(t).execute(&s.db).await}let mut r=ok(json!({"ok":true})).into_response();r.headers_mut().insert(header::SET_COOKIE,HeaderValue::from_static("rohbar_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"));r}

async fn shipments(State(s):State<SharedState>,h:HeaderMap)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let r=if u.role=="customer"{sqlx::query_as::<_,Shipment>("SELECT id,from_city,to_city,date,cargo,weight,vehicle,price,status,company FROM shipments WHERE customer_id=$1 ORDER BY created_at DESC").bind(u.id).fetch_all(&s.db).await}else{sqlx::query_as::<_,Shipment>("SELECT id,from_city,to_city,date,cargo,weight,vehicle,price,status,company FROM shipments ORDER BY created_at DESC").fetch_all(&s.db).await};match r{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load shipments")}}
async fn create_shipment(State(s):State<SharedState>,h:HeaderMap,Json(v):Json<Value>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};if u.role!="customer"&&u.role!="admin"{return err(StatusCode::FORBIDDEN,"FORBIDDEN","Only customers can create shipments")};let g=|k:&str|v.get(k).and_then(Value::as_str).unwrap_or("").to_string();let id=format!("RH-{}",Uuid::new_v4().simple());let r=sqlx::query_as::<_,Shipment>("INSERT INTO shipments(id,customer_id,from_city,to_city,date,cargo,weight,vehicle,price,status,company) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'published',$10) RETURNING id,from_city,to_city,date,cargo,weight,vehicle,price,status,company").bind(&id).bind(u.id).bind(g("from")).bind(g("to")).bind(g("date")).bind(g("cargo")).bind(g("weight")).bind(g("vehicle")).bind(g("price")).bind(u.name).fetch_one(&s.db).await;let Ok(sh)=r else{return err(StatusCode::BAD_REQUEST,"VALIDATION_ERROR","Could not create shipment")};let _=append_event(&s,&id,u.id,"shipment.created",json!({})).await;ok(sh).into_response()}
async fn shipment(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>)->Response{if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,Shipment>("SELECT id,from_city,to_city,date,cargo,weight,vehicle,price,status,company FROM shipments WHERE id=$1").bind(id).fetch_optional(&s.db).await{Ok(Some(v))=>ok(v).into_response(),Ok(None)=>err(StatusCode::NOT_FOUND,"NOT_FOUND","Shipment not found"),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load shipment")}}
async fn shipment_events(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>)->Response{if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,ShipmentEvent>("SELECT id,shipment_id,event,actor_id,payload,occurred_at FROM shipment_events WHERE shipment_id=$1 ORDER BY occurred_at").bind(id).fetch_all(&s.db).await{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load events")}}
async fn append_event(s:&SharedState,sid:&str,actor:Uuid,kind:&str,payload:Value)->Result<(),sqlx::Error>{let mut tx=s.db.begin().await?;let id=Uuid::new_v4();sqlx::query("INSERT INTO shipment_events(id,shipment_id,event,actor_id,payload) VALUES($1,$2,$3,$4,$5)").bind(id).bind(sid).bind(kind).bind(actor).bind(&payload).execute(&mut *tx).await?;sqlx::query("INSERT INTO outbox_events(id,event_type,aggregate_id,actor_id,payload) VALUES($1,$2,$3,$4,$5)").bind(id).bind(kind).bind(sid).bind(actor).bind(&payload).execute(&mut *tx).await?;tx.commit().await?;let sh=sqlx::query_as::<_,Shipment>("SELECT id,from_city,to_city,date,cargo,weight,vehicle,price,status,company FROM shipments WHERE id=$1").bind(sid).fetch_optional(&s.db).await.ok().flatten();let ev=sqlx::query_as::<_,ShipmentEvent>("SELECT id,shipment_id,event,actor_id,payload,occurred_at FROM shipment_events WHERE id=$1").bind(id).fetch_one(&s.db).await?;let _=s.realtime.send(RealtimeMessage{r#type:"shipment.event".into(),shipment:sh,event:Some(ev),notification:None});Ok(())}
async fn status(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>,Json(i):Json<StatusInput>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let cur=sqlx::query_scalar::<_,String>("SELECT status FROM shipments WHERE id=$1").bind(&id).fetch_optional(&s.db).await.ok().flatten();let Some(cur)=cur else{return err(StatusCode::NOT_FOUND,"NOT_FOUND","Shipment not found")};if !matches!((cur.as_str(),i.status.as_str()),("published","offered")|("offered","accepted")|("accepted","in_transit")|("in_transit","delivered")|("delivered","completed")){return err(StatusCode::CONFLICT,"INVALID_TRANSITION","Invalid shipment status transition")};let Ok(sh)=sqlx::query_as::<_,Shipment>("UPDATE shipments SET status=$1 WHERE id=$2 RETURNING id,from_city,to_city,date,cargo,weight,vehicle,price,status,company").bind(&i.status).bind(&id).fetch_one(&s.db).await else{return err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not update shipment")};let _=append_event(&s,&id,u.id,if i.status=="completed"{"shipment.completed"}else{"shipment.status_changed"},json!({"status":i.status})).await;ok(sh).into_response()}

async fn offers(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>)->Response{if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,Offer>("SELECT id,shipment_id,carrier_id,carrier_name,vehicle,price,eta,status FROM offers WHERE shipment_id=$1 ORDER BY created_at DESC").bind(id).fetch_all(&s.db).await{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load offers")}}
async fn create_offer(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>,Json(i):Json<OfferInput>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};if u.role!="carrier"&&u.role!="admin"{return err(StatusCode::FORBIDDEN,"FORBIDDEN","Only carriers can create offers")};let oid=format!("OF-{}",Uuid::new_v4().simple());let r=sqlx::query_as::<_,Offer>("INSERT INTO offers(id,shipment_id,carrier_id,carrier_name,vehicle,price,eta,status) VALUES($1,$2,$3,$4,$5,$6,$7,'pending') RETURNING id,shipment_id,carrier_id,carrier_name,vehicle,price,eta,status").bind(&oid).bind(&id).bind(u.id).bind(&u.name).bind(i.vehicle).bind(i.price).bind(i.eta).fetch_one(&s.db).await;let Ok(o)=r else{return err(StatusCode::BAD_REQUEST,"VALIDATION_ERROR","Could not create offer")};let _=sqlx::query("UPDATE shipments SET status='offered' WHERE id=$1 AND status='published'").bind(&id).execute(&s.db).await;let _=append_event(&s,&id,u.id,"offer.created",json!(o)).await;ok(o).into_response()}
async fn accept_offer(State(s):State<SharedState>,h:HeaderMap,Path(oid):Path<String>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};if u.role!="customer"&&u.role!="admin"{return err(StatusCode::FORBIDDEN,"FORBIDDEN","Only customers can accept offers")};let mut tx=match s.db.begin().await{Ok(v)=>v,Err(_)=>return err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Transaction failed")};let Some(o)=sqlx::query_as::<_,Offer>("SELECT id,shipment_id,carrier_id,carrier_name,vehicle,price,eta,status FROM offers WHERE id=$1 FOR UPDATE").bind(&oid).fetch_optional(&mut *tx).await.ok().flatten()else{return err(StatusCode::NOT_FOUND,"NOT_FOUND","Offer not found")};let _=sqlx::query("UPDATE offers SET status=CASE WHEN id=$1 THEN 'accepted' ELSE 'rejected' END WHERE shipment_id=$2").bind(&oid).bind(&o.shipment_id).execute(&mut *tx).await;let _=sqlx::query("UPDATE shipments SET status='accepted' WHERE id=$1").bind(&o.shipment_id).execute(&mut *tx).await;if tx.commit().await.is_err(){return err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not accept offer")};let _=append_event(&s,&o.shipment_id,u.id,"offer.accepted",json!(o)).await;ok(o).into_response()}

async fn fleet(State(s):State<SharedState>,h:HeaderMap)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,FleetVehicle>("SELECT id,plate,model,body,capacity,volume,status,driver_name FROM fleet_vehicles WHERE owner_id=$1 ORDER BY id").bind(u.id).fetch_all(&s.db).await{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load fleet")}}
async fn create_fleet(State(s):State<SharedState>,h:HeaderMap,Json(v):Json<Value>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let g=|k:&str|v.get(k).and_then(Value::as_str).unwrap_or("");let id=format!("VH-{}",Uuid::new_v4().simple());match sqlx::query_as::<_,FleetVehicle>("INSERT INTO fleet_vehicles(id,owner_id,plate,model,body,capacity,volume,status,driver_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,plate,model,body,capacity,volume,status,driver_name").bind(id).bind(u.id).bind(g("plate")).bind(g("model")).bind(g("body")).bind(g("capacity")).bind(g("volume")).bind(g("status")).bind(v.get("driverName").and_then(Value::as_str)).fetch_one(&s.db).await{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::BAD_REQUEST,"VALIDATION_ERROR","Could not create vehicle")}}
async fn driver_list(State(s):State<SharedState>,h:HeaderMap)->Response{if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,DriverAssignment>("SELECT shipment_id,driver_id,driver_name,phone,vehicle_id,vehicle_plate FROM driver_assignments ORDER BY assigned_at DESC").fetch_all(&s.db).await{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load assignments")}}
async fn driver_assign(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>,Json(i):Json<DriverInput>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};if u.role!="carrier"&&u.role!="admin"{return err(StatusCode::FORBIDDEN,"FORBIDDEN","Only carriers can assign drivers")};let r=sqlx::query_as::<_,DriverAssignment>("INSERT INTO driver_assignments(shipment_id,driver_id,driver_name,phone,vehicle_id,vehicle_plate) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(shipment_id) DO UPDATE SET driver_id=EXCLUDED.driver_id,driver_name=EXCLUDED.driver_name,phone=EXCLUDED.phone,vehicle_id=EXCLUDED.vehicle_id,vehicle_plate=EXCLUDED.vehicle_plate RETURNING shipment_id,driver_id,driver_name,phone,vehicle_id,vehicle_plate").bind(&id).bind(i.driver_id).bind(i.driver_name).bind(i.phone).bind(i.vehicle_id).bind(i.vehicle_plate).fetch_one(&s.db).await;let Ok(v)=r else{return err(StatusCode::BAD_REQUEST,"VALIDATION_ERROR","Could not assign driver")};let _=append_event(&s,&id,u.id,"driver.assigned",json!(v)).await;ok(v).into_response()}
async fn notifications(State(s):State<SharedState>,h:HeaderMap)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,NotificationItem>("SELECT id,title,text,type,read,created_at FROM notifications WHERE user_id=$1 ORDER BY created_at DESC").bind(u.id).fetch_all(&s.db).await{Ok(v)=>ok(v).into_response(),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not load notifications")}}
async fn notification_read(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<Uuid>)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};match sqlx::query_as::<_,NotificationItem>("UPDATE notifications SET read=true WHERE id=$1 AND user_id=$2 RETURNING id,title,text,type,read,created_at").bind(id).bind(u.id).fetch_optional(&s.db).await{Ok(Some(v))=>ok(v).into_response(),Ok(None)=>err(StatusCode::NOT_FOUND,"NOT_FOUND","Notification not found"),Err(_)=>err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not update notification")}}
async fn notification_all(State(s):State<SharedState>,h:HeaderMap)->Response{let Some(u)=user(&s,&h).await else{return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let _=sqlx::query("UPDATE notifications SET read=true WHERE user_id=$1").bind(u.id).execute(&s.db).await;ok(json!({"ok":true})).into_response()}

fn verify_telegram(data:&str,token:&str)->Option<(i64,String)>{let mut hash=None;let mut pairs=Vec::new();let mut id=None;let mut name=None;for raw in data.split('&'){let(k,v)=raw.split_once('=')?;let value=urlencoding::decode(v).ok()?.into_owned();if k=="hash"{hash=Some(value)}else{if k=="user"{let u:Value=serde_json::from_str(&value).ok()?;id=u.get("id").and_then(Value::as_i64);name=u.get("first_name").and_then(Value::as_str).map(str::to_owned)}pairs.push(format!("{k}={value}"))}}pairs.sort_unstable();let mut mac=HmacSha256::new_from_slice(b"WebAppData").ok()?;mac.update(token.as_bytes());let secret=mac.finalize().into_bytes();let mut check=HmacSha256::new_from_slice(&secret).ok()?;check.update(pairs.join("\n").as_bytes());let expected=hex::encode(check.finalize().into_bytes());if hash.as_deref()!=Some(expected.as_str()){return None}Some((id?,name.unwrap_or_else(||"Telegram user".into())))}
async fn telegram_auth(State(s):State<SharedState>,Json(i):Json<TelegramAuth>)->Response{let Some(t)=s.telegram_token.as_deref()else{return err(StatusCode::SERVICE_UNAVAILABLE,"TELEGRAM_DISABLED","Telegram authentication is not configured")};let Some((tg,name))=verify_telegram(&i.init_data,t)else{return err(StatusCode::UNAUTHORIZED,"INVALID_TELEGRAM_AUTH","Telegram initData verification failed")};let u=match sqlx::query_as::<_,User>("SELECT id,name,role,phone,telegram_id FROM users WHERE telegram_id=$1").bind(tg).fetch_optional(&s.db).await.ok().flatten(){Some(v)=>v,None=>{match sqlx::query_as::<_,User>("INSERT INTO users(id,email,name,password_hash,role,telegram_id) VALUES($1,$2,$3,'telegram','customer',$4) RETURNING id,name,role,phone,telegram_id").bind(Uuid::new_v4()).bind(format!("telegram:{tg}@rohbar.local")).bind(name).bind(tg).fetch_one(&s.db).await{Ok(v)=>v,Err(_)=>return err(StatusCode::INTERNAL_SERVER_ERROR,"DB_ERROR","Could not create Telegram user")}}};let Ok(st)=new_session(&s,u.id).await else{return err(StatusCode::INTERNAL_SERVER_ERROR,"SESSION_ERROR","Could not create session")};let mut r=ok(u).into_response();r.headers_mut().insert(header::SET_COOKIE,HeaderValue::from_str(&set_cookie(&st,s.session_cookie_secure)).unwrap());r}
async fn automation_event(State(s):State<SharedState>,h:HeaderMap,Json(i):Json<EventInput>)->Response{if let Some(secret)=&s.automation_secret{if h.get("x-automation-secret").and_then(|v|v.to_str().ok())!=Some(secret){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Invalid automation secret")}}else if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let actor=user(&s,&h).await.map(|u|u.id).unwrap_or(Uuid::nil());let exists=sqlx::query_scalar::<_,bool>("SELECT EXISTS(SELECT 1 FROM shipment_events WHERE id=$1)").bind(i.id).fetch_one(&s.db).await.unwrap_or(false);if exists{return ok(json!({"accepted":true,"duplicate":true})).into_response()};let _=sqlx::query("INSERT INTO shipment_events(id,shipment_id,event,actor_id,payload) VALUES($1,$2,$3,$4,$5)").bind(i.id).bind(&i.aggregate_id).bind(&i.event).bind(actor).bind(&i.payload).execute(&s.db).await;let _=sqlx::query("INSERT INTO outbox_events(id,event_type,aggregate_id,actor_id,payload) VALUES($1,$2,$3,$4,$5)").bind(i.id).bind(&i.event).bind(&i.aggregate_id).bind(actor).bind(&i.payload).execute(&s.db).await;ok(json!({"accepted":true,"duplicate":false})).into_response()}

async fn sse(State(s):State<SharedState>,h:HeaderMap,Path(id):Path<String>)->Response{if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let rx=s.realtime.subscribe();let stream=BroadcastStream::new(rx).filter_map(move|x|match x{Ok(v) if v.shipment.as_ref().map(|z|z.id==id).unwrap_or(false)=>serde_json::to_string(&v).ok().map(|d|Ok::<Event,Infallible>(Event::default().data(d))),_=>None});Sse::new(stream).keep_alive(KeepAlive::default()).into_response()}
async fn ws(State(s):State<SharedState>,h:HeaderMap,upgrade:WebSocketUpgrade,Query(q):Query<RealtimeQuery>)->Response{if user(&s,&h).await.is_none(){return err(StatusCode::UNAUTHORIZED,"UNAUTHORIZED","Session is not authenticated")};let rx=s.realtime.subscribe();upgrade.on_upgrade(move|socket|ws_loop(socket,rx,q.shipment_id))}
async fn ws_loop(mut socket:WebSocket,mut rx:broadcast::Receiver<RealtimeMessage>,shipment_id:Option<String>){loop{tokio::select!{m=rx.recv()=>match m{Ok(v)=>{if shipment_id.as_ref().map(|id|v.shipment.as_ref().map(|s|&s.id==id).unwrap_or(false)).unwrap_or(true){if let Ok(text)=serde_json::to_string(&v){if socket.send(Message::Text(text.into())).await.is_err(){break}}}},Err(broadcast::error::RecvError::Lagged(_))=>continue,Err(_)=>break},incoming=socket.recv()=>match incoming{Some(Ok(Message::Ping(v)))=>{if socket.send(Message::Pong(v)).await.is_err(){break}},Some(Ok(Message::Close(_)))|None=>break,_=>{}}}}}

async fn automation_worker(s:SharedState){let mut tick=tokio::time::interval(std::time::Duration::from_secs(2));loop{tick.tick().await;let rows=sqlx::query_as::<_,(Uuid,String,String,Uuid,Value)>("SELECT id,event_type,aggregate_id,actor_id,payload FROM outbox_events WHERE published_at IS NULL ORDER BY created_at LIMIT 100").fetch_all(&s.db).await.unwrap_or_default();if rows.is_empty(){continue}let Ok(mut redis)=s.redis.get_multiplexed_async_connection().await else{continue};for(id,kind,aggregate,actor,payload)in rows{let message=json!({"id":id,"type":kind,"aggregateId":aggregate,"actorId":actor,"payload":payload});if redis.publish::<_,_,i32>("rohbar:events",serde_json::to_string(&message).unwrap_or_default()).await.is_ok(){let _=sqlx::query("UPDATE outbox_events SET published_at=NOW() WHERE id=$1 AND published_at IS NULL").bind(id).execute(&s.db).await}}}}

#[tokio::main]
async fn main(){tracing_subscriber::fmt().with_env_filter(env::var("RUST_LOG").unwrap_or_else(|_|"info".into())).init();dotenvy::dotenv().ok();let db=PgPoolOptions::new().max_connections(env::var("DATABASE_MAX_CONNECTIONS").ok().and_then(|v|v.parse().ok()).unwrap_or(20)).connect(&env::var("DATABASE_URL").expect("DATABASE_URL is required")).await.expect("database connection failed");sqlx::migrate!("./migrations").run(&db).await.expect("database migration failed");let redis=redis::Client::open(env::var("REDIS_URL").expect("REDIS_URL is required")).expect("redis configuration failed");let origin_text=env::var("FRONTEND_ORIGIN").unwrap_or_else(|_|"https://app.vosiev.com".into());let origin=origin_text.parse::<HeaderValue>().expect("invalid FRONTEND_ORIGIN");let(tx,_)=broadcast::channel(512);let state=Arc::new(AppState{db,redis,realtime:tx,telegram_token:env::var("TELEGRAM_BOT_TOKEN").ok().filter(|v|!v.is_empty()),telegram_webhook_secret:env::var("TELEGRAM_WEBHOOK_SECRET").ok().filter(|v|!v.is_empty()),session_cookie_secure:env::var("SESSION_COOKIE_SECURE").map(|v|v!="false").unwrap_or(true),frontend_origin:origin_text,automation_secret:env::var("AUTOMATION_SECRET").ok().filter(|v|!v.is_empty())});let worker=state.clone();tokio::spawn(automation_worker(worker));let app=Router::new().route("/api/v1/health",get(health)).route("/api/v1/about",get(about)).route("/api/v1/auth/me",get(me)).route("/api/v1/auth/login",post(login)).route("/api/v1/auth/register",post(register)).route("/api/v1/auth/logout",post(logout)).route("/api/v1/auth/telegram",post(telegram_auth)).route("/api/v1/shipments",get(shipments).post(create_shipment)).route("/api/v1/shipments/:id",get(shipment)).route("/api/v1/shipments/:id/events",get(shipment_events)).route("/api/v1/shipments/:id/status",post(status)).route("/api/v1/shipments/:id/offers",get(offers).post(create_offer)).route("/api/v1/offers/:id/accept",post(accept_offer)).route("/api/v1/fleet",get(fleet).post(create_fleet)).route("/api/v1/drivers/assignments",get(driver_list)).route("/api/v1/shipments/:id/driver",post(driver_assign)).route("/api/v1/notifications",get(notifications)).route("/api/v1/notifications/:id/read",post(notification_read)).route("/api/v1/notifications/read-all",post(notification_all)).route("/api/v1/events",post(automation_event)).route("/api/v1/shipments/:id/stream",get(sse)).route("/api/v1/ws",get(ws)).route("/api/v1/telegram/webhook",post(telegram::webhook)).with_state(state).layer(CorsLayer::new().allow_origin(origin).allow_credentials(true).allow_methods(tower_http::cors::Any).allow_headers(tower_http::cors::Any)).layer(TraceLayer::new_for_http());let bind=env::var("BIND_ADDR").unwrap_or_else(|_|"0.0.0.0:8080".into());info!("RohBar API listening on {bind}");let listener=tokio::net::TcpListener::bind(&bind).await.expect("bind failed");axum::serve(listener,app).await.expect("server failed")}
